### PR TITLE
Add ji_fisher() as 🙏 to Carrie Fisher (closes #22)

### LINKED ISSUE #22: 🙃 Add a function that will replace each letter with an emoji
_An ode to my favorite princess_. 
Carrie Fisher often wrote in emojis by replacing each letter with an emoji that resembled it. For example,

```r
emo::ji_fisher("without you I would just be a weird chick in a hat")
#> 〰ℹ✝️♓️🅾️⛎✝️ ✌🏻️🅾️⛎ ℹ 〰🅾️⛎🕒d 🌶⛎💲✝️ 🅱️📧🅰️ 〰ℹ📧®d ©♓️ℹ©🎋 ℹ️♑️ 🅰️ ♓️🅰️✝️
```
ref: [tweet](https://twitter.com/carrieffisher/status/804114429071630336)
```r
emo::ji_fisher("Im supposed to tell you to buy my book, but Im not really like that!")
#> ℹ♏️ 💲⛎🅿️🅿️🅾️💲📧d ✝️🅾️ ✝️📧🕒🕒 ✌🏻️🅾️⛎ ✝️🅾️ 🅱️⛎✌🏻️ ♏️✌🏻️ 🅱️🅾️🅾️🎋, 🅱️⛎✝️ ℹ♏️ ♑️🅾️✝️ ®📧🅰️🕒🕒✌🏻️ 🕒ℹ🎋📧 ✝️♓️🅰️✝️❕
```
ref: [tweet](https://twitter.com/carrieffisher/status/803307648057679872)

```r
emo::ji_fisher("I love the new rstudio")
#> ℹ️   👍❤️✌️📧  🌴♓️📧  🆕   ®️⚡️🌴⛎↩️ℹ️⭕️
```

A bit similar to #5, but different in that rather than replace full words, it would just replace letters.

### PR DESCRIPTION
**Pull request by LucyMcGowan**

### CODE REVIEW

**Comment by romainfrancois** [comment]
perhaps we can just leave `fisher_lst` unexported, i.e. maybe it does not need its own file in `data/`

I don't think it would be a big deal to move the content of `data-raw/fisher.R` to `emojis.R` so that we would spare the file in `data/` and just use one `use_data( internal = TRUE)` call without the `save`and `load` dance. 

Also, not sure why it shows changes in the json file, as I don't think you use it for this PR.

**Comment by LucyMcGowan** [comment]
I couldn't find a way to use `devtools::use_data()` in two separate files (both emoji.R and fisher.R) which is why I do the saving/loading dance - do you know how to go about that? The .json file was recreated because I reran emoji.R and it turned out there were a few updates to the document it pulled from.

**Comment by romainfrancois** [comment]
I actually did not know about `overwrite=FALSE` before I look at this repo 🙊. 

Alternatively maybe we could export it, it might make sense to view the alphabet anyway, so doing a `use_data( fisher_lst, overwrite = TRUE )`

**Comment by LucyMcGowan** [comment]
👌 do you have a different name that you'd prefer other than `fisher_lst` if we're exporting?

**Comment by romainfrancois** [comment]
Can't think of anything that ✔️, we can always change it later.

**Pull request merged**
